# Stubs for handler (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any, Callable, Union

from sanic.response import HTTPResponse

class Handler:
    no_authorization: Callable[[Exception], Union[HTTPResponse, Any]] = ...
